### ISSUE TITLE
RGB Color Generator

### ISSUE THREAD

**Issue by SyedaMahamFahim** [Abdulwahid7027/Frontend-Mini-Projects#1]
A while back, I created an RGB Color Generator that I think could be helpful for beginners working in frontend development, especially in vanilla JavaScript. I'm interested in contributing this project to Hacktoberfest and adding it to this repository. Please let me know if this is something you're interested in, and I'll create a pull request in October.

[Project Link ](https://github.com/SyedaMahamFahim/Vanilla-JavaScript-Projects/tree/master/RGB%20Color%20Generator)

**Comment by abhaygzb15** [comment]
@SyedaMahamFahim I am interested in working upon this.

**Comment by Abdulwahid7027** [comment]
@SyedaMahamFahim You can add it.

**Comment by Abdulwahid7027** [comment]
Sorry @abhaygzb15 it assigned for other one. If you wish, you can add some other mini project and let me know by creating Issue.

**Comment by SyedaMahamFahim** [comment]
Thank you, Abdulwahid7027. I will be creating a pull request during Hacktoberfest.
